### PR TITLE
ignore test flags

### PR DESCRIPTION
**Pull request by capt-hb**

### CODE REVIEW

**Comment by cihangir** [comment]
Hi @capt-hb What is the motivation behind this PR and what will happen if someone uses "multiconfig" within their compiled tests?

**Comment by capt-hb** [comment]
Shouldn't break any code, multiconfig should ignore test.* flags, there was an issue about it a while ago but it got closed. (#40)
I've been using multiconfig in multiple projects but this was bothering me, that's why I made a PR for it.

**Comment by calvernaz** [comment]
Any plans to merge this?

**Comment by cihangir** [comment]
Thanks for the contribution @capt-hb

**Pull request merged**
